name: flutter_windowmanager
description: A Flutter plugin for manipulating Android WindowManager LayoutParams.
version: 0.0.2
authors:
- Paul Mundt <paul.mundt@adaptant.io>
- Adaptant Labs <labs@adaptant.io>
homepage: https://www.github.com/adaptant-labs/flutter_windowmanager
repository: https://www.github.com/adaptant-labs/flutter_windowmanager
issue_tracker: https://github.com/adaptant-labs/flutter_windowmanager/issues

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.adaptant.labs.flutter_windowmanager
        pluginClass: FlutterWindowManagerPlugin
